#!/bin/bash
set -x -e


cat > /home/hadoop/accumulo.sh << 'EOF2'
if ps ax | grep -v grep | egrep "datanode|namenode"> /dev/null
then

		
if [ ! -d "/home/hadoop/accumulo" ]; then



#Change swappiness and IPV6 disable
echo -e "net.ipv6.conf.all.disable_ipv6 = 1" | sudo tee --append /etc/sysctl.conf
echo -e "net.ipv6.conf.default.disable_ipv6 = 1" | sudo tee --append /etc/sysctl.conf
echo -e "net.ipv6.conf.lo.disable_ipv6 = 1" | sudo tee --append /etc/sysctl.conf
echo -e "vm.swappiness = 10" | sudo tee --append /etc/sysctl.conf

sudo sysctl -w vm.swappiness=10

echo -e "" | sudo tee --append /etc/security/limits.conf
echo -e "*\t\tsoft\tnofile\t65536" | sudo tee --append /etc/security/limits.conf
echo -e "*\t\thard\tnofile\t65536" | sudo tee --append /etc/security/limits.conf

USER=accumulo
USERPW=secret
ACCUMULO_INSTANCE=instance
HOMEDIR=/home/hadoop
ZOOKEEPRERV=3.4.6
ZOO_LOG_DIR=/mnt/var/log/zookeeper
EMR_BUCKET=elasticmapreduce.bootstrapactions
ACCUMULOV=1.6.1
ACCUMULO_TSERVER_OPTS=1GB


#Add accumulo user
sudo adduser $USER
sudo sh -c "echo '$USERPW' | passwd $USER --stdin"

mkdir -p $HOMEDIR/.versions
cd $HOMEDIR/.versions

# Zookeper installed with EMR so skip all this!
##Installing Zookeeper
#echo "Downloading Zookeeper"
#wget http://apache.mirrors.tds.net/zookeeper/stable/zookeeper-${ZOOKEEPRERV}.tar.gz
#tar xzf zookeeper*tar.gz
#ln -sf $HOMEDIR/.versions/zookeeper-${ZOOKEEPRERV}  $HOMEDIR/zookeeper
#
##Run only on master
#if grep isMaster /mnt/var/lib/info/instance.json | grep true;
#then
#sudo -u zookeper mkdir -p ${ZOO_LOG_DIR}/log
#sudo -u zookeper mkdir -p ${ZOO_LOG_DIR}/data
#echo "clientPort=2181" > $HOMEDIR/zookeeper/conf/zoo.cfg
#echo "dataDir=${ZOO_LOG_DIR}/snapshot" >> $HOMEDIR/zookeeper/conf/zoo.cfg
#echo "syncLimit=5" >> $HOMEDIR/zookeeper/conf/zoo.cfg
#echo "tickTime=2000" >> $HOMEDIR/zookeeper/conf/zoo.cfg
#echo "initLimit=10" >> $HOMEDIR/zookeeper/conf/zoo.cfg
#echo "maxClientCnxns=100" >> $HOMEDIR/zookeeper/conf/zoo.cfg
#echo "dataLogDir=${ZOO_LOG_DIR}/data" >> $HOMEDIR/zookeeper/conf/zoo.cfg
#echo "Starting Zookeeper..."
#export ZOO_LOG_DIR=${ZOO_LOG_DIR}
#$HOMEDIR/zookeeper/bin/zkServer.sh start
#fi


#Install accumulo

cd $HOMEDIR/.versions
wget http://${EMR_BUCKET}.s3.amazonaws.com/accumulo/${ACCUMULOV}/accumulo-${ACCUMULOV}-bin.tar.gz

tar -xvzf accumulo-${ACCUMULOV}-bin.tar.gz
ln -sf $HOMEDIR/.versions/accumulo-$ACCUMULOV $HOMEDIR/accumulo

sudo yum install -y expect


cp $HOMEDIR/accumulo/conf/examples/${ACCUMULO_TSERVER_OPTS}/standalone/* $HOMEDIR/accumulo/conf/

#Get Zookeeper IP address
if grep isMaster /mnt/var/lib/info/instance.json | grep true;
then
ZK_IPADDR=`curl http://169.254.169.254/latest/meta-data/local-ipv4`
else
ZK_IPADDR=`xmllint /etc/hadoop/conf/yarn-site.xml  --xpath "//configuration/property[name='yarn.resourcemanager.hostname']/value/text()"`
fi

echo Master=$ZK_IPADDR

#Update accumulo-site.xml
sed -i "s/<value>localhost:2181<\/value>/<value>${ZK_IPADDR}:2181<\/value>/" $HOMEDIR/accumulo/conf/accumulo-site.xml
#sed -i "s/<value>root<\/value>/<value>accumulo<\/value><\/property><property><name>trace.password<\/name><value>secret<\/value>/" $HOMEDIR/accumulo/conf/accumulo-site.xml


cat >> $HOMEDIR/accumulo/conf/accumulo-env.sh  << EOF
export ACCUMULO_HOME=/home/hadoop/accumulo
export HADOOP_HOME=/home/hadoop
export ACCUMULO_LOG_DIR=/mnt/var/log/accumulo
export JAVA_HOME=/usr/lib/jvm/java
export ZOOKEEPER_HOME=/usr/lib/zookeeper
export HADOOP_PREFIX=/usr/lib/hadoop
export HADOOP_CONF_DIR=/etc/hadoop/conf
EOF

echo "Fixed accumulo-env"

hostname > $HOMEDIR/accumulo/conf/monitor
hostname > $HOMEDIR/accumulo/conf/gc
hostname > $HOMEDIR/accumulo/conf/tracers
hostname > $HOMEDIR/accumulo/conf/gc
hostname > $HOMEDIR/accumulo/conf/slaves

echo "added hostname to slaces, tracers, etc."

#Run on master/slave based on configuration
if grep isMaster /mnt/var/lib/info/instance.json | grep true;
then

echo "I am master"

	hostname > $HOMEDIR/accumulo/conf/masters

	export ACCUMULO_HOME=/home/hadoop/accumulo
	export HADOOP_HOME=/home/hadoop
	export ACCUMULO_LOG_DIR=/mnt/var/log/accumulo
	export JAVA_HOME=/usr/lib/jvm/java
	export ZOOKEEPER_HOME=/usr/lib/zookeeper
	export HADOOP_PREFIX=/usr/lib/hadoop
	export HADOOP_CONF_DIR=/etc/hadoop/conf
	
	#Create Accumulo HDFS location
	/usr/bin/hadoop fs -mkdir /accumulo
	/usr/bin/hadoop fs -chown -R $USER:$USER /accumulo
echo "Hadooping done"

	mkdir -p /mnt/var/log/accumulo/logs/
	sudo chown $USER:$USER -R /mnt/var/log/accumulo
	sudo -u $USER $HOMEDIR/accumulo/bin/accumulo init --clear-instance-name --instance-name $ACCUMULO_INSTANCE --password $USERPW	
echo "accumulo inited"

else
echo "I am slave"
	mkdir -p /mnt/var/log/accumulo/logs/
	sudo chown $USER:$USER -R /mnt/var/log/accumulo
	MASTER=`xmllint /etc/hadoop/conf/yarn-site.xml  --xpath "//configuration/property[name='yarn.resourcemanager.hostname']/value/text()"`
	echo $MASTER > $HOMEDIR/accumulo/conf/masters	
echo "$MASTER is master"
fi

echo "$USER will $HOMEDIR/accumulo/bin/start-here.sh now"
sudo -u $USER  $HOMEDIR/accumulo/bin/start-here.sh
echo "did it"
sudo sed -i 's/.*accumulo.*//' /etc/crontab
fi
fi
EOF2



sudo sh -c "echo '*/1     * * * *   hadoop     bash /home/hadoop/accumulo.sh > /home/hadoop/cron.log 2>&1 ' >> /etc/crontab"
