#!/bin/bash
set -x -e

#Change swappiness and IPV6 disable
echo -e "net.ipv6.conf.all.disable_ipv6 = 1" | sudo tee --append /etc/sysctl.conf
echo -e "net.ipv6.conf.default.disable_ipv6 = 1" | sudo tee --append /etc/sysctl.conf
echo -e "net.ipv6.conf.lo.disable_ipv6 = 1" | sudo tee --append /etc/sysctl.conf
echo -e "vm.swappiness = 10" | sudo tee --append /etc/sysctl.conf

sudo sysctl -w vm.swappiness=10

echo -e "" | sudo tee --append /etc/security/limits.conf
echo -e "*\t\tsoft\tnofile\t65536" | sudo tee --append /etc/security/limits.conf
echo -e "*\t\thard\tnofile\t65536" | sudo tee --append /etc/security/limits.conf

USER=accumulo

#Add accumulo user
sudo adduser $USER
#sudo sh -c "echo '$USERPW' | passwd $USER --stdin"

cat > /home/accumulo/accumulo.sh << 'EOF2'

USER=accumulo
USERPW=secret
ACCUMULO_INSTANCE=instance
HOMEDIR=/home/accumulo
ACCUMULOV=1.8.0
ACCUMULO_TSERVER_OPTS=3GB

mkdir -p $HOMEDIR/.versions

#Install accumulo

cd $HOMEDIR/.versions
wget -q http://mirrors.ukfast.co.uk/sites/ftp.apache.org/accumulo/1.8.0/accumulo-${ACCUMULOV}-bin.tar.gz

tar -xvzf accumulo-${ACCUMULOV}-bin.tar.gz
ln -sf $HOMEDIR/.versions/accumulo-$ACCUMULOV $HOMEDIR/accumulo


cp $HOMEDIR/accumulo/conf/examples/${ACCUMULO_TSERVER_OPTS}/standalone/* $HOMEDIR/accumulo/conf/

#Get Zookeeper IP address
if grep isMaster /mnt/var/lib/info/instance.json | grep true;
then
	ZK_IPADDR=`curl http://169.254.169.254/latest/meta-data/local-ipv4`
else
	ZK_IPADDR=`xmllint /etc/hadoop/conf/yarn-site.xml  --xpath "//configuration/property[name='yarn.resourcemanager.hostname']/value/text()"`
fi

echo Master=$ZK_IPADDR

#Update accumulo-site.xml
sed -i "s/<value>localhost:2181<\/value>/<value>${ZK_IPADDR}:2181<\/value>/" $HOMEDIR/accumulo/conf/accumulo-site.xml


cat >> $HOMEDIR/accumulo/conf/accumulo-env.sh  << EOF
export ACCUMULO_HOME=/home/accumulo/accumulo
export HADOOP_HOME=/home/hadoop
export ACCUMULO_LOG_DIR=/mnt/var/log/accumulo
export JAVA_HOME=/usr/lib/jvm/java
export ZOOKEEPER_HOME=/usr/lib/zookeeper
export HADOOP_PREFIX=/usr/lib/hadoop
export HADOOP_CONF_DIR=/etc/hadoop/conf
EOF

echo "Fixed accumulo-env"

hostname > $HOMEDIR/accumulo/conf/gc
hostname > $HOMEDIR/accumulo/conf/tracers
hostname > $HOMEDIR/accumulo/conf/gc
hostname > $HOMEDIR/accumulo/conf/slaves

echo "added hostname to slaces, tracers, etc."

#Run on master/slave based on configuration
if grep isMaster /mnt/var/lib/info/instance.json | grep true;
then
	echo "I am master"
	hostname > $HOMEDIR/accumulo/conf/masters
	hostname > $HOMEDIR/accumulo/conf/monitor
	. $HOMEDIR/accumulo/conf/accumulo-env.sh	
	#Create Accumulo HDFS location
	/usr/bin/hadoop fs -mkdir /accumulo
	/usr/bin/hadoop fs -chown -R $USER:$USER /accumulo

	mkdir -p /mnt/var/log/accumulo/logs/
	$HOMEDIR/accumulo/bin/accumulo init --clear-instance-name --instance-name $ACCUMULO_INSTANCE --password $USERPW	
	echo "accumulo initialised"

else
	echo "I am slave"
	mkdir -p /mnt/var/log/accumulo/logs/
	MASTER=`xmllint /etc/hadoop/conf/yarn-site.xml  --xpath "//configuration/property[name='yarn.resourcemanager.hostname']/value/text()"`
	echo $MASTER > $HOMEDIR/accumulo/conf/masters	
	echo $MASTER > $HOMEDIR/accumulo/conf/monitor
	echo "$MASTER is master"
fi

$HOMEDIR/accumulo/bin/start-here.sh
fi
EOF2



sudo -u accumulo /home/accumulo/accumulo.sh > /home/accumulo/init.log 
